# Generated by Django 5.2.12 on 2026-04-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Lazer', 'Lazer'), ('Contas', 'Contas'), ('Saúde', 'Saúde'), ('Educação', 'Educação'), ('Outros', 'Outros')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
