# Generated by Django 5.2.12 on 2026-04-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('alimentacao', 'alimentacao'), ('transporte', 'transporte'), ('lazer', 'lazer'), ('contas', 'contas'), ('saude', 'saude'), ('educacao', 'educacao'), ('outros', 'outros')], max_length=50),
        ),
    ]
