# Generated by Django 5.2.12 on 2026-04-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('lazer', 'Lazer'), ('contas', 'Contas'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('outros', 'Outros')], max_length=50),
        ),
    ]
